- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"

- name: "question"
  description: "Further information is requested"
  color: "d876e3"

- name: "priority::high"
  description: "priorityg high"
  color: "d93f0b"

- name: "priority::low"
  description: "priority low"
  color: "9dcce0"

- name: "priority::medium"
  description: "priority medium"
  color: "fbca04"

- name: "major update"
  color: "B60205"
  description: "Major update"

- name: "minor update"
  color: "EFFA85"
  description: "Minor update"

- name: "patch"
  color: "08C036"
  description: "Patch"

- name: "tools"
  description: ""
  color: "510f70"

- name: "C2A"
  description: ""
  color: "2a9637"

- name: "S2E"
  description: ""
  color: "eef789"

- name: "WINGS"
  description: ""
  color: "1503bb"

- name: "automation::force-check-format"
  description: ""
  color: "9A9379"
